Page({
    data: {
        style: "",
        seat: [{
            "id": "2804",
            "no": "001",
            "name": "001",
            "area": "25",
            "category": "1",
            "point_x": "16.25",
            "point_x2": null,
            "point_x3": null,
            "point_x4": null,
            "point_y": "22.037037",
            "point_y2": null,
            "point_y3": null,
            "point_y4": null,
            "width": "2.291",
            "height": "3.2786879999999998",
            "status": "1",
            "status_name": "空闲",
            "area_name": "5F-S阅览区",
            "area_levels": "3",
            "area_type": "1",
            "area_color": null,
            "in_label": 1
        },
            {
                "id": "2805",
                "no": "002",
                "name": "002",
                "area": "25",
                "category": "1",
                "point_x": "18.54167",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "21.407910000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.953713",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2806",
                "no": "003",
                "name": "003",
                "area": "25",
                "category": "1",
                "point_x": "20.72917",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "21.31148",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.857281",
                "status": "3",
                "status_name": "锁定",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2807",
                "no": "004",
                "name": "004",
                "area": "25",
                "category": "1",
                "point_x": "16.45833",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "25.94021",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2808",
                "no": "005",
                "name": "005",
                "area": "25",
                "category": "1",
                "point_x": "18.80208",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "26.13308",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2809",
                "no": "006",
                "name": "006",
                "area": "25",
                "category": "1",
                "point_x": "20.88542",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "26.13308",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2810",
                "no": "007",
                "name": "007",
                "area": "25",
                "category": "1",
                "point_x": "16.51042",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "31.822569999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2811",
                "no": "008",
                "name": "008",
                "area": "25",
                "category": "1",
                "point_x": "18.75",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "31.6297",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.6666669999999999",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2812",
                "no": "009",
                "name": "009",
                "area": "25",
                "category": "1",
                "point_x": "20.72917",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "31.6297",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2813",
                "no": "010",
                "name": "010",
                "area": "25",
                "category": "1",
                "point_x": "16.40625",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "36.25844",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2814",
                "no": "011",
                "name": "011",
                "area": "25",
                "category": "1",
                "point_x": "18.64583",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "36.25844",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2815",
                "no": "012",
                "name": "012",
                "area": "25",
                "category": "1",
                "point_x": "20.98958",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "36.354869999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.2786879999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2816",
                "no": "013",
                "name": "013",
                "area": "25",
                "category": "1",
                "point_x": "16.30208",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "43.47079",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.1354169999999999",
                "height": "3.375121",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2817",
                "no": "014",
                "name": "014",
                "area": "25",
                "category": "1",
                "point_x": "18.75",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "41.947929999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.2786879999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2818",
                "no": "015",
                "name": "015",
                "area": "25",
                "category": "1",
                "point_x": "20.88542",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "41.947929999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.5679850000000002",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2819",
                "no": "016",
                "name": "016",
                "area": "25",
                "category": "1",
                "point_x": "16.45833",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "46.383800000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2820",
                "no": "017",
                "name": "017",
                "area": "25",
                "category": "1",
                "point_x": "18.80208",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "46.576659999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.6666669999999999",
                "height": "3.1822560000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2821",
                "no": "018",
                "name": "018",
                "area": "25",
                "category": "1",
                "point_x": "20.88542",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "46.673099999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2822",
                "no": "019",
                "name": "019",
                "area": "25",
                "category": "1",
                "point_x": "16.45833",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "52.362580000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2823",
                "no": "020",
                "name": "020",
                "area": "25",
                "category": "1",
                "point_x": "18.69792",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "52.266150000000003",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2824",
                "no": "021",
                "name": "021",
                "area": "25",
                "category": "1",
                "point_x": "20.83333",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "52.459009999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2825",
                "no": "022",
                "name": "022",
                "area": "25",
                "category": "1",
                "point_x": "16.5625",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "56.702030000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.4715530000000001",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2826",
                "no": "023",
                "name": "023",
                "area": "25",
                "category": "1",
                "point_x": "18.85417",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "56.894889999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.6145830000000001",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2827",
                "no": "024",
                "name": "024",
                "area": "25",
                "category": "1",
                "point_x": "20.83333",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "56.798459999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2828",
                "no": "025",
                "name": "025",
                "area": "25",
                "category": "1",
                "point_x": "16.5625",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "62.391509999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.71875",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2829",
                "no": "026",
                "name": "026",
                "area": "25",
                "category": "1",
                "point_x": "18.69792",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "63.487949999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2830",
                "no": "027",
                "name": "027",
                "area": "25",
                "category": "1",
                "point_x": "20.78125",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "62.295079999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.953713",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2831",
                "no": "028",
                "name": "028",
                "area": "25",
                "category": "1",
                "point_x": "16.51042",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "66.827380000000005",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.71875",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2832",
                "no": "029",
                "name": "029",
                "area": "25",
                "category": "1",
                "point_x": "18.69792",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "66.923820000000006",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.375121",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2833",
                "no": "030",
                "name": "030",
                "area": "25",
                "category": "1",
                "point_x": "20.83333",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "66.827380000000005",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2834",
                "no": "031",
                "name": "031",
                "area": "25",
                "category": "1",
                "point_x": "16.5625",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "72.613299999999995",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2835",
                "no": "032",
                "name": "032",
                "area": "25",
                "category": "1",
                "point_x": "18.69792",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "72.709739999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.71875",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2836",
                "no": "033",
                "name": "033",
                "area": "25",
                "category": "1",
                "point_x": "20.67708",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "72.51688",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2837",
                "no": "034",
                "name": "034",
                "area": "25",
                "category": "1",
                "point_x": "16.5625",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "76.856319999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2838",
                "no": "035",
                "name": "035",
                "area": "25",
                "category": "1",
                "point_x": "18.85417",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "76.856319999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.5625",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2839",
                "no": "036",
                "name": "036",
                "area": "25",
                "category": "1",
                "point_x": "20.83333",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "76.759889999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.6644169999999998",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2840",
                "no": "037",
                "name": "037",
                "area": "25",
                "category": "1",
                "point_x": "28.22917",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.074250000000006",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2841",
                "no": "038",
                "name": "038",
                "area": "25",
                "category": "1",
                "point_x": "28.28125",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "83.317260000000005",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.1822560000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2842",
                "no": "039",
                "name": "039",
                "area": "25",
                "category": "1",
                "point_x": "30.46875",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.074250000000006",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.1354169999999999",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2843",
                "no": "040",
                "name": "040",
                "area": "25",
                "category": "1",
                "point_x": "30.72917",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "83.027959999999993",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.0833330000000001",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2844",
                "no": "041",
                "name": "041",
                "area": "25",
                "category": "1",
                "point_x": "38.489579999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.363550000000004",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.1822560000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2845",
                "no": "042",
                "name": "042",
                "area": "25",
                "category": "1",
                "point_x": "38.541670000000003",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "82.931529999999995",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.2786879999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2846",
                "no": "043",
                "name": "043",
                "area": "25",
                "category": "1",
                "point_x": "41.145829999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "78.881389999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2847",
                "no": "044",
                "name": "044",
                "area": "25",
                "category": "1",
                "point_x": "41.145829999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "82.931529999999995",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.2786879999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2848",
                "no": "045",
                "name": "045",
                "area": "25",
                "category": "1",
                "point_x": "49.635420000000003",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.074250000000006",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2849",
                "no": "046",
                "name": "046",
                "area": "25",
                "category": "1",
                "point_x": "49.583329999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "82.931529999999995",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2850",
                "no": "047",
                "name": "047",
                "area": "25",
                "category": "1",
                "point_x": "51.875",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "78.784959999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.1875",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2851",
                "no": "048",
                "name": "048",
                "area": "25",
                "category": "1",
                "point_x": "52.03125",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "83.220830000000007",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2852",
                "no": "049",
                "name": "049",
                "area": "25",
                "category": "1",
                "point_x": "60.104170000000003",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.170680000000004",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.6145830000000001",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2853",
                "no": "050",
                "name": "050",
                "area": "25",
                "category": "1",
                "point_x": "60.0",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "83.124399999999994",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.71875",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2854",
                "no": "051",
                "name": "051",
                "area": "25",
                "category": "1",
                "point_x": "62.239579999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "79.267120000000006",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2855",
                "no": "052",
                "name": "052",
                "area": "25",
                "category": "1",
                "point_x": "62.552079999999997",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "83.317260000000005",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.0858240000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2856",
                "no": "053",
                "name": "053",
                "area": "25",
                "category": "1",
                "point_x": "68.541659999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "76.663449999999997",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "4.0501449999999997",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2857",
                "no": "054",
                "name": "054",
                "area": "25",
                "category": "1",
                "point_x": "70.885409999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "76.952749999999995",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2858",
                "no": "055",
                "name": "055",
                "area": "25",
                "category": "1",
                "point_x": "68.75",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "72.806179999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.0858240000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2859",
                "no": "056",
                "name": "056",
                "area": "25",
                "category": "1",
                "point_x": "70.729159999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "72.709739999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.1875",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2860",
                "no": "057",
                "name": "057",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "66.730959999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2861",
                "no": "058",
                "name": "058",
                "area": "25",
                "category": "1",
                "point_x": "70.833340000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "66.730959999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.6644169999999998",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2862",
                "no": "059",
                "name": "059",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "62.295079999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "3.4715530000000001",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2863",
                "no": "060",
                "name": "060",
                "area": "25",
                "category": "1",
                "point_x": "70.833340000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "62.584380000000003",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.8229169999999999",
                "height": "2.9893930000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2864",
                "no": "061",
                "name": "061",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "56.605589999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2865",
                "no": "062",
                "name": "062",
                "area": "25",
                "category": "1",
                "point_x": "70.78125",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "56.412730000000003",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.0833330000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2866",
                "no": "063",
                "name": "063",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "51.976860000000002",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2867",
                "no": "064",
                "name": "064",
                "area": "25",
                "category": "1",
                "point_x": "70.833340000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "52.169719999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.375121",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2868",
                "no": "065",
                "name": "065",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "46.190939999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.5679850000000002",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2869",
                "no": "066",
                "name": "066",
                "area": "25",
                "category": "1",
                "point_x": "70.729159999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "46.094499999999996",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.5679850000000002",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2870",
                "no": "067",
                "name": "067",
                "area": "25",
                "category": "1",
                "point_x": "68.645840000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "41.947929999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9791669999999999",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2871",
                "no": "068",
                "name": "068",
                "area": "25",
                "category": "1",
                "point_x": "70.833340000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "41.851489999999998",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.9270830000000001",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2872",
                "no": "069",
                "name": "069",
                "area": "25",
                "category": "1",
                "point_x": "68.541659999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "36.25844",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.0833330000000001",
                "height": "3.7608489999999999",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2873",
                "no": "070",
                "name": "070",
                "area": "25",
                "category": "1",
                "point_x": "70.885409999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "36.065570000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.0833330000000001",
                "height": "3.953713",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2874",
                "no": "071",
                "name": "071",
                "area": "25",
                "category": "1",
                "point_x": "68.645840000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "31.822569999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.953713",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2875",
                "no": "072",
                "name": "072",
                "area": "25",
                "category": "1",
                "point_x": "70.572909999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "31.822569999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "3.6644169999999998",
                "status": "1",
                "status_name": "空闲",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2876",
                "no": "073",
                "name": "073",
                "area": "25",
                "category": "1",
                "point_x": "68.645840000000007",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "25.843779999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "3.4715530000000001",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2877",
                "no": "074",
                "name": "074",
                "area": "25",
                "category": "1",
                "point_x": "70.885409999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "26.325939999999999",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.875",
                "height": "3.375121",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2878",
                "no": "075",
                "name": "075",
                "area": "25",
                "category": "1",
                "point_x": "68.59375",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "21.407910000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "1.7708330000000001",
                "height": "4.1465769999999997",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            },
            {
                "id": "2879",
                "no": "076",
                "name": "076",
                "area": "25",
                "category": "1",
                "point_x": "70.729159999999993",
                "point_x2": null,
                "point_x3": null,
                "point_x4": null,
                "point_y": "21.407910000000001",
                "point_y2": null,
                "point_y3": null,
                "point_y4": null,
                "width": "2.03125",
                "height": "4.0501449999999997",
                "status": "6",
                "status_name": "使用中",
                "area_name": "5F-S阅览区",
                "area_levels": "3",
                "area_type": "1",
                "area_color": null,
                "in_label": 1
            }
        ],
        seatList: [],
        SelelctSeatIndex: -1,
        t: -1,
    },


    handleSeatTap(e) {
        this.setData({
            SelectSeatIndex: e.currentTarget.dataset.index,
        });
    },

///
//     bottom: 354
//     dataset: {}
//     height: 240
//     id: ""
//     left: 14.699999809265137
//     right: 415.69999980926514
//     top: 114
//     width: 401
    load(e) {
        console.log(e)
    },


    onReady(e) {
        let that = this
        var list = this.data.seat
        var seat = []
        const query = wx.createSelectorQuery();
        query.select('.background').boundingClientRect(function (res) {
            console.log(res)
            list.forEach((item, index) => {
                var style =
                    "height:" + parseFloat(item.height) * res.height / 100 + "px;" +
                    "width:" + parseFloat(item.width) * res.width / 100 + "px;" +
                    "left:" + parseFloat(item.point_x) * res.width / 100 + "px;" +
                    "top:" + item.point_y * res.height / 100 + "px;" +
                    "background-position:-" + parseFloat(item.point_x) * res.width / 100 + "px -" + (parseFloat(item.point_y)) * res.height / 100 + "px;" +
                    "background-size:" + res.width + "px"
                console.log(style)
                seat.push({
                    style: style
                })
            })
            that.setData({
                seatList: seat
            })

        }).exec(function (rect) {
            console.log(rect[0])
            // rect返回一个数组，需要使用下标0才能找到
            // console.log(s[0].height)
        });
    }
})
