spring:
      datasource:
        url: jdbc:mysql://122.51.61.24:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#        url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

        username: spring
        password: bJd4LAPypmJixiex
        driver-class-name: com.mysql.cj.jdbc.Driver
      redis:
        host: 122.51.61.24
#        host: 127.0.0.1
        port: 6379
        timeout: 10000
        database: 0
        password: Panhuiyu666.


